# Generated by Django 5.2.1 on 2025-05-27 15:32

from django.db import migrations
import datetime


def set_joining_date(apps, schema_editor):
    UserProfile = apps.get_model('accounts', 'UserProfile')
    # Set joining_date to user's date_joined for existing profiles
    for profile in UserProfile.objects.all():
        if not profile.joining_date:
            profile.joining_date = profile.user.date_joined.date()
            profile.save()


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0006_recreate_userprofile'),
    ]

    operations = [
        migrations.RunPython(set_joining_date, migrations.RunPython.noop),
    ]
