# Generated by Django 5.2.1 on 2025-05-27 16:00

from django.db import migrations


def set_default_teacher(apps, schema_editor):
    Assignment = apps.get_model('assignments', 'Assignment')
    UserProfile = apps.get_model('accounts', 'UserProfile')
    
    # Get the first teacher in the system
    teacher = UserProfile.objects.filter(role='teacher').first()
    
    if teacher:
        # Update all assignments without a teacher
        Assignment.objects.filter(teacher__isnull=True).update(teacher=teacher)


def reverse_set_teacher(apps, schema_editor):
    # No need to do anything when unapplying the migration
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_alter_assignment_options_alter_submission_options_and_more'),
        ('accounts', '0001_initial'),  # Make sure this is the correct dependency
    ]

    operations = [
        migrations.RunPython(set_default_teacher, reverse_set_teacher),
    ]
