# Generated by Django 5.2.1 on 2025-06-03 08:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='tags',
            field=models.CharField(blank=True, help_text='Enter tags separated by commas (e.g., python, django, web development)', max_length=200),
        ),
        migrations.AlterField(
            model_name='resource',
            name='description',
            field=models.TextField(help_text='Describe what this resource is about and how it can help others.'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='external_link',
            field=models.URLField(blank=True, help_text='Add a link to an external resource (e.g., YouTube video, website)', null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='file',
            field=models.FileField(blank=True, help_text='Upload a file (PDF, Word, PPT, code files, or media)', null=True, upload_to='resources/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'ppt', 'pptx', 'txt', 'py', 'js', 'html', 'css', 'jpg', 'png', 'mp4'])]),
        ),
        migrations.AlterField(
            model_name='resource',
            name='resource_type',
            field=models.CharField(choices=[('document', 'Document'), ('video', 'Video'), ('link', 'External Link'), ('presentation', 'Presentation'), ('code', 'Code Snippet'), ('other', 'Other')], max_length=20),
        ),
    ]
